name: command-dispatcher

on:
  issue_comment:
    types:
      - created

jobs:
  trigger:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}

    permissions: write-all

    steps:

#      - name: checkout
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: '0'

      # since this action is triggered by a comment, for the next steps we need
      # to know the head ref of the pull request in which this comment appeared
      # so that we can check out the correct working tree
      - name: Check comment author request validity
        uses: actions/github-script@v6
        with:
          # TODO: Custom token is not needed here, permissions: write-all covers this.
          #github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const helpers = require('./scripts/actions-script-helpers.js');
            helpers.validateApplyCommand(github, context, core);